#!/usr/bin/env node
/**
 * Embeds ../RUNBOOK.md into a TypeScript module so it's available at runtime
 * on Vercel (where fs access to parent directories isn't possible).
 */
const fs = require("fs");
const path = require("path");

const runbookPath = path.join(__dirname, "..", "..", "RUNBOOK.md");
const outPath = path.join(__dirname, "..", "src", "lib", "runbook-content.generated.ts");

const content = fs.readFileSync(runbookPath, "utf-8");
const escaped = JSON.stringify(content);

fs.writeFileSync(
  outPath,
  `// Auto-generated by scripts/embed-runbook.js — do not edit\nexport const RUNBOOK_CONTENT = ${escaped};\n`
);

console.log(`Embedded RUNBOOK.md (${content.length} chars) → ${outPath}`);
